package com.fluvian.sdk.core

/**
 * File: AnalyticsTracker.kt
 * Description: Minimal playback analytics hooks (privacy-first; no PII in default implementations).
 * Author: monigarr@monigarr.com
 * Date: 2026-04-12
 * Version: 1.3.6
 *
 * Usage:
 *   Implement for your pipeline or use [NoOpAnalyticsTracker] during bring-up.
 *
 * Usage example:
 *   StreamingClientImpl(context, analytics = object : AnalyticsTracker { … }, drmConfig = null)
 */
interface AnalyticsTracker {
    fun onPlay()
    fun onBufferStart()
    fun onBufferEnd()
    fun onError(error: Throwable)

    /**
     * Privacy-minimized playback session boundary: [sessionId] is an opaque UUID generated by the SDK
     * (no account, device advertising ID, or stream URL).
     */
    fun onSessionStart(sessionId: String) = Unit

    /** Pairs with [onSessionStart] when the client is released or re-initialized. */
    fun onSessionEnd(sessionId: String) = Unit

    /**
     * Optional sports or editorial timeline signal (IDs only; no PII). Integrators may forward to
     * observability pipelines; default is a no-op so existing implementations keep compiling.
     */
    fun onSportsEventMarker(markerId: String) = Unit

    /**
     * Enterprise hook: invoked on the main thread after [com.fluvian.sdk.core.StreamingClient.initialize] applies a
     * [com.fluvian.sdk.core.StreamConfig]. Contains capability flags and optional tenant key from white-label branding
     * only — never stream URLs, API keys, or DRM material.
     */
    fun onStreamInitialized(summary: AnalyticsStreamConfigSummary) = Unit

    /** Optional coarse playback state for observability (state names align with [androidx.media3.common.Player.State]). */
    fun onPlaybackStateChanged(playbackState: Int) = Unit

    /** Optional seek funnel signal; positions are player timeline milliseconds (not wall clock). */
    fun onSeek(fromPositionMs: Long, toPositionMs: Long) = Unit
}

/**
 * Privacy-bounded snapshot for [AnalyticsTracker.onStreamInitialized] — safe to log or forward to SIEM pipelines
 * when policies allow coarse capability telemetry.
 */
data class AnalyticsStreamConfigSummary(
    val bandwidthPredictorHints: Boolean,
    val alwaysOnAiOptimization: Boolean,
    val aiProviderTypeName: String?,
    val analyticsTenantKey: String?,
    /** Count of [com.fluvian.sdk.core.StreamConfig.clientMetadata] entries (keys only; values are never forwarded here). */
    val clientMetadataEntryCount: Int = 0,
)

/** No-op implementation for integrators that defer analytics wiring. */
object NoOpAnalyticsTracker : AnalyticsTracker {
    override fun onPlay() = Unit
    override fun onBufferStart() = Unit
    override fun onBufferEnd() = Unit
    override fun onError(error: Throwable) = Unit
}
