package com.monigarr.streamkit.core

/**
 * File: AnalyticsTracker.kt
 * Description: Minimal playback analytics hooks (privacy-first; no PII in default implementations).
 * Author: monigarr@monigarr.com
 * Date: 2026-04-12
 * Version: 1.3.4
 *
 * Usage:
 *   Implement for your pipeline or use [NoOpAnalyticsTracker] during bring-up.
 *
 * Usage example:
 *   StreamingClientImpl(context, analytics = object : AnalyticsTracker { … }, drmConfig = null)
 */
interface AnalyticsTracker {
    fun onPlay()
    fun onBufferStart()
    fun onBufferEnd()
    fun onError(error: Throwable)

    /**
     * Privacy-minimized playback session boundary: [sessionId] is an opaque UUID generated by the SDK
     * (no account, device advertising ID, or stream URL).
     */
    fun onSessionStart(sessionId: String) = Unit

    /** Pairs with [onSessionStart] when the client is released or re-initialized. */
    fun onSessionEnd(sessionId: String) = Unit

    /**
     * Optional sports or editorial timeline signal (IDs only; no PII). Integrators may forward to
     * observability pipelines; default is a no-op so existing implementations keep compiling.
     */
    fun onSportsEventMarker(markerId: String) = Unit
}

/** No-op implementation for integrators that defer analytics wiring. */
object NoOpAnalyticsTracker : AnalyticsTracker {
    override fun onPlay() = Unit
    override fun onBufferStart() = Unit
    override fun onBufferEnd() = Unit
    override fun onError(error: Throwable) = Unit
}
